CREATE TABLE TB_CLIENTES(
    CPF VARCHAR2(11),
    NOME VARCHAR2(100),
    ENDERECO1 VARCHAR2(150),
    ENDERECO2 VARCHAR2(150),
    BAIRRO VARCHAR2(50),
    CIDADE VARCHAR2(50),
    ESTADO VARCHAR2(2), 
    CEP VARCHAR2(8),
    DATA_NASCIMENTO DATE,
    IDADE INTEGER,
    SEXO VARCHAR2(1),
    LIMITE_CREDITO NUMBER(15,2),
    VOLUME_COMPRA NUMBER,
    PRIMEIRA_COMPRA NUMBER(1)
);



CREATE TABLE TB_VENDEDORES(
    MATRICULA VARCHAR(5), 
    NOME VARCHAR(100), 
    DATA_ADMISSAO DATE,
    PERCENTUAL_COMISSAO NUMBER
);

SELECT * FROM TB_CLIENTES;
SELECT * FROM TB_VENDEDORES;
SELECT * FROM TB_PRODUTOS;


INSERT INTO TB_CLIENTES (CPF, NOME, ENDERECO1, ENDERECO2, BAIRRO, CIDADE, ESTADO, CEP, DATA_NASCIMENTO, IDADE, SEXO, LIMITE_CREDITO, VOLUME_COMPRA, PRIMEIRA_COMPRA)
VALUES ('12345678901', 'JoÃ£o da Silva', 'Rua das Flores, 123', 'Apto 101', 'Centro', 'SÃ£o Paulo', 'SP', '01001000', TO_DATE('1980-05-20', 'YYYY-MM-DD'), 44, 'M', 10000.00, 15000.50, 1);


INSERT INTO TB_VENDEDORES (MATRICULA, NOME, DATA_ADMISSAO, PERCENTUAL_COMISSAO) 
VALUES ('V001', 'João Silva', TO_DATE('2023-03-15', 'YYYY-MM-DD'), 0.05);

INSERT INTO TB_VENDEDORES (MATRICULA, NOME, DATA_ADMISSAO, PERCENTUAL_COMISSAO) 
VALUES ('V002', 'Maria Oliveira', TO_DATE('2021-06-01', 'YYYY-MM-DD'), 0.07);



//Exclusão de dados
DROP TABLE TB_CLIENTES3;
DROP TABLE TB_CLIENTES2;


//Inserção de dados em tabelas

INSERT INTO TB_PRODUTOS(PRODUTO,NOME,EMBALAGEM,TAMANHO,SABOR,PRECO_LISTA)
VALUES('1040107', 'Light - 350ml - Melância', 'Lata', '350 ml', 'Melância', 4.56);


INSERT INTO TB_PRODUTOS(PRODUTO,NOME,EMBALAGEM,TAMANHO,SABOR,PRECO_LISTA)
VALUES('1037797', 'Clean - 2 litros - Laranja', 'Pet', '2 litros', 'laranja', 16.01);


INSERT INTO TB_PRODUTOS(PRODUTO,NOME,EMBALAGEM,TAMANHO,SABOR,PRECO_LISTA)
VALUES('1000889', 'Sabor da Montanha', 'Garrafa', '700 ml', 'laranja', 6.31);

INSERT INTO TB_VENDEDORES(MATRICULA,NOME,DATA_ADMISSAO,PERCENTUAL_COMISSAO)
VALUES('00233', 'João Geraldo da Fonseca', TO_DATE('2021-11-15', 'YYYY-MM-DD'), 20.0);

INSERT INTO TB_VENDEDORES(MATRICULA,NOME,DATA_ADMISSAO,PERCENTUAL_COMISSAO)
VALUES('00400', 'Maria do Rosario', TO_DATE('2012-08-23', 'YYYY-MM-DD'), 0.15);


INSERT INTO TB_VENDEDORES(MATRICULA,NOME,DATA_ADMISSAO,PERCENTUAL_COMISSAO)
VALUES('00810', 'Marcia Almeida', TO_DATE('2016-12-14', 'YYYY-MM-DD'), 0.18);

INSERT INTO TB_VENDEDORES(MATRICULA,NOME,DATA_ADMISSAO,PERCENTUAL_COMISSAO)
VALUES('00414', 'Carlos Moreira', TO_DATE('2015-11-13', 'YYYY-MM-DD'), 0.14);

INSERT INTO TB_VENDEDORES(MATRICULA,NOME,DATA_ADMISSAO,PERCENTUAL_COMISSAO)
VALUES('00934', 'Juvenildo Martins', TO_DATE('2010-09-03', 'YYYY-MM-DD'), 0.20);

SELECT * FROM TB_PRODUTOS;
SELECT * FROM TB_VENDEDORES;
SELECT * FROM TB_CLIENTES;


//Alteração de registros
SELECT * FROM TB_PRODUTOS;

UPDATE TB_PRODUTOS SET EMBALAGEM = 'Lata' where PRODUTO = '1037797';

UPDATE TB_PRODUTOS SET NOME = 'Clenan - 350 ML - Laranja', TAMANHO = '350 ML', PRECO_LISTA = 5.50;



UPDATE TB_VENDEDORES SET PERCENTUAL_COMISSAO = 0.18 WHERE MATRICULA = '00233';

UPDATE TB_VENDEDORES SET PERCENTUAL_COMISSAO = 0.18 WHERE MATRICULA = '00400';

UPDATE TB_VENDEDORES SET PERCENTUAL_COMISSAO = 0.18 WHERE MATRICULA = '00414';

SELECT * FROM TB_VENDEDORES;



//Excluir linha da tabela 
select * from tb_produtos;

DELETE FROM TB_PRODUTOS WHERE PRODUTO = '1037797';


SELECT * FROM TB_VENDEDORES;

DELETE FROM TB_VENDEDORES WHERE MATRICULA = '00400';



